name: exptech_service
description: Designed by ExpTech

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  loggy: ^2.0.1+1
  flutter_loggy: ^2.0.1
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  lottie: ^1.2.1
  platform_device_id: ^1.0.1
  device_info_plus: ^3.2.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  universal_io: ^2.0.4
  web_socket_channel: ^2.1.0
  flutter_markdown: ^0.6.9
  package_info_plus: ^1.4.0
  flutter_launcher_icons: ^0.9.2
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.20
  clipboard: ^0.1.3

  overlay_support: ^1.2.1
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ExpTech_Home.png"

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
